/* tslint:disable */
/* eslint-disable */
/**
 * Learn API
 * Technicks Learn API with authentication, courses, and gamification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ChangePasswordDto
 */
export interface ChangePasswordDto {
    /**
     * Current password
     * @type {string}
     * @memberof ChangePasswordDto
     */
    'currentPassword': string;
    /**
     * New password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof ChangePasswordDto
     */
    'newPassword': string;
}
/**
 * 
 * @export
 * @interface CourseCheckInDto
 */
export interface CourseCheckInDto {
    /**
     * Local calendar date as YYYY-MM-DD. Defaults to server date.
     * @type {string}
     * @memberof CourseCheckInDto
     */
    'date'?: string;
}
/**
 * 
 * @export
 * @interface CreateCategoryDto
 */
export interface CreateCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'name': string;
    /**
     * Optional. Auto-generated from name if omitted.
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface CreateCommentDto
 */
export interface CreateCommentDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCommentDto
     */
    'body': string;
    /**
     * Parent comment ID for nested replies
     * @type {string}
     * @memberof CreateCommentDto
     */
    'parentId'?: string;
}
/**
 * 
 * @export
 * @interface CreateCourseCategoryDto
 */
export interface CreateCourseCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCourseCategoryDto
     */
    'name': string;
    /**
     * Optional. Auto-generated from name if omitted.
     * @type {string}
     * @memberof CreateCourseCategoryDto
     */
    'slug'?: string;
}
/**
 * 
 * @export
 * @interface CreateCourseDto
 */
export interface CreateCourseDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCourseDto
     */
    'title': string;
    /**
     * URL slug; defaults to a slugified title
     * @type {string}
     * @memberof CreateCourseDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseDto
     */
    'status'?: CreateCourseDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateCourseDto
     */
    'sortOrder'?: number;
    /**
     * CourseCategory id to assign; null clears it
     * @type {string}
     * @memberof CreateCourseDto
     */
    'categoryId'?: string;
}

export const CreateCourseDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED'
} as const;

export type CreateCourseDtoStatusEnum = typeof CreateCourseDtoStatusEnum[keyof typeof CreateCourseDtoStatusEnum];

/**
 * 
 * @export
 * @interface CreateLessonBlockDto
 */
export interface CreateLessonBlockDto {
    /**
     * Order of the block inside the lesson
     * @type {number}
     * @memberof CreateLessonBlockDto
     */
    'blockIndex'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonBlockDto
     */
    'kind': CreateLessonBlockDtoKindEnum;
    /**
     * Markdown/plain content for HEADING and TEXT blocks
     * @type {string}
     * @memberof CreateLessonBlockDto
     */
    'text'?: string;
    /**
     * Remote URL for IMAGE and VIDEO blocks
     * @type {string}
     * @memberof CreateLessonBlockDto
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonBlockDto
     */
    'caption'?: string;
}

export const CreateLessonBlockDtoKindEnum = {
    Heading: 'HEADING',
    Text: 'TEXT',
    Image: 'IMAGE',
    Video: 'VIDEO'
} as const;

export type CreateLessonBlockDtoKindEnum = typeof CreateLessonBlockDtoKindEnum[keyof typeof CreateLessonBlockDtoKindEnum];

/**
 * 
 * @export
 * @interface CreateLessonDto
 */
export interface CreateLessonDto {
    /**
     * 
     * @type {string}
     * @memberof CreateLessonDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonDto
     */
    'courseId': string;
    /**
     * URL slug; defaults to a slugified title
     * @type {string}
     * @memberof CreateLessonDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonDto
     */
    'status'?: CreateLessonDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateLessonDto
     */
    'sortOrder'?: number;
    /**
     * 
     * @type {Array<CreateLessonBlockDto>}
     * @memberof CreateLessonDto
     */
    'blocks'?: Array<CreateLessonBlockDto>;
}

export const CreateLessonDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED'
} as const;

export type CreateLessonDtoStatusEnum = typeof CreateLessonDtoStatusEnum[keyof typeof CreateLessonDtoStatusEnum];

/**
 * 
 * @export
 * @interface CreatePostDto
 */
export interface CreatePostDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'excerpt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'status'?: CreatePostDtoStatusEnum;
    /**
     * Array of category IDs
     * @type {Array<string>}
     * @memberof CreatePostDto
     */
    'categoryIds'?: Array<string>;
}

export const CreatePostDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;

export type CreatePostDtoStatusEnum = typeof CreatePostDtoStatusEnum[keyof typeof CreatePostDtoStatusEnum];

/**
 * 
 * @export
 * @interface ForgotPasswordDto
 */
export interface ForgotPasswordDto {
    /**
     * Email to send OTP to
     * @type {string}
     * @memberof ForgotPasswordDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface LoginDto
 */
export interface LoginDto {
    /**
     * User email address
     * @type {string}
     * @memberof LoginDto
     */
    'email': string;
    /**
     * User password
     * @type {string}
     * @memberof LoginDto
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
    /**
     * User email address
     * @type {string}
     * @memberof RegisterDto
     */
    'email': string;
    /**
     * Password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof RegisterDto
     */
    'password': string;
    /**
     * Full legal name
     * @type {string}
     * @memberof RegisterDto
     */
    'fullName'?: string;
}
/**
 * 
 * @export
 * @interface ResendOtpDto
 */
export interface ResendOtpDto {
    /**
     * Email pending verification to resend the OTP to
     * @type {string}
     * @memberof ResendOtpDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface ResetPasswordDto
 */
export interface ResetPasswordDto {
    /**
     * 6-digit OTP from email
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'token': string;
    /**
     * New password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'newPassword': string;
}
/**
 * 
 * @export
 * @interface SetUsernameDto
 */
export interface SetUsernameDto {
    /**
     * Desired username (3-30 chars, letters/numbers/underscores)
     * @type {string}
     * @memberof SetUsernameDto
     */
    'username': string;
}
/**
 * 
 * @export
 * @interface UpdateCategoryDto
 */
export interface UpdateCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'name'?: string;
    /**
     * Optional. Auto-generated from name if omitted.
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface UpdateCourseDto
 */
export interface UpdateCourseDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'status'?: UpdateCourseDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof UpdateCourseDto
     */
    'sortOrder'?: number;
    /**
     * CourseCategory id to assign; null clears it
     * @type {object}
     * @memberof UpdateCourseDto
     */
    'categoryId'?: object;
}

export const UpdateCourseDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED'
} as const;

export type UpdateCourseDtoStatusEnum = typeof UpdateCourseDtoStatusEnum[keyof typeof UpdateCourseDtoStatusEnum];

/**
 * 
 * @export
 * @interface UpdateLessonDto
 */
export interface UpdateLessonDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'courseId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'status'?: UpdateLessonDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof UpdateLessonDto
     */
    'sortOrder'?: number;
    /**
     * Replaces all blocks when provided
     * @type {Array<CreateLessonBlockDto>}
     * @memberof UpdateLessonDto
     */
    'blocks'?: Array<CreateLessonBlockDto>;
}

export const UpdateLessonDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED'
} as const;

export type UpdateLessonDtoStatusEnum = typeof UpdateLessonDtoStatusEnum[keyof typeof UpdateLessonDtoStatusEnum];

/**
 * 
 * @export
 * @interface UpdatePostDto
 */
export interface UpdatePostDto {
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'excerpt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'status'?: UpdatePostDtoStatusEnum;
    /**
     * Array of category IDs
     * @type {Array<string>}
     * @memberof UpdatePostDto
     */
    'categoryIds'?: Array<string>;
}

export const UpdatePostDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;

export type UpdatePostDtoStatusEnum = typeof UpdatePostDtoStatusEnum[keyof typeof UpdatePostDtoStatusEnum];

/**
 * 
 * @export
 * @interface VerifyEmailDto
 */
export interface VerifyEmailDto {
    /**
     * Email that received the verification OTP
     * @type {string}
     * @memberof VerifyEmailDto
     */
    'email': string;
    /**
     * 6-digit OTP sent to the email
     * @type {string}
     * @memberof VerifyEmailDto
     */
    'token': string;
}

/**
 * LearnApi - axios parameter creator
 * @export
 */
export const LearnApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Mark a lesson as completed and award XP
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        learnControllerCompleteV1: async (slug: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('learnControllerCompleteV1', 'slug', slug)
            const localVarPath = `/api/v1/learn/lessons/{slug}/complete`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a lesson (admin or instructor)
         * @param {CreateLessonDto} createLessonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        learnControllerCreateV1: async (createLessonDto: CreateLessonDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createLessonDto' is not null or undefined
            assertParamExists('learnControllerCreateV1', 'createLessonDto', createLessonDto)
            const localVarPath = `/api/v1/learn/lessons`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createLessonDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get published lessons
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        learnControllerFindAllV1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/learn/lessons`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a lesson by slug with its content blocks
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        learnControllerFindBySlugV1: async (slug: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('learnControllerFindBySlugV1', 'slug', slug)
            const localVarPath = `/api/v1/learn/lessons/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a lesson (admin or instructor)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        learnControllerRemoveV1: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('learnControllerRemoveV1', 'id', id)
            const localVarPath = `/api/v1/learn/lessons/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a lesson (admin or instructor)
         * @param {string} id 
         * @param {UpdateLessonDto} updateLessonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        learnControllerUpdateV1: async (id: string, updateLessonDto: UpdateLessonDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('learnControllerUpdateV1', 'id', id)
            // verify required parameter 'updateLessonDto' is not null or undefined
            assertParamExists('learnControllerUpdateV1', 'updateLessonDto', updateLessonDto)
            const localVarPath = `/api/v1/learn/lessons/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateLessonDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LearnApi - functional programming interface
 * @export
 */
export const LearnApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LearnApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Mark a lesson as completed and award XP
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async learnControllerCompleteV1(slug: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.learnControllerCompleteV1(slug, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LearnApi.learnControllerCompleteV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a lesson (admin or instructor)
         * @param {CreateLessonDto} createLessonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async learnControllerCreateV1(createLessonDto: CreateLessonDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.learnControllerCreateV1(createLessonDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LearnApi.learnControllerCreateV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get published lessons
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async learnControllerFindAllV1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.learnControllerFindAllV1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LearnApi.learnControllerFindAllV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a lesson by slug with its content blocks
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async learnControllerFindBySlugV1(slug: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.learnControllerFindBySlugV1(slug, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LearnApi.learnControllerFindBySlugV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a lesson (admin or instructor)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async learnControllerRemoveV1(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.learnControllerRemoveV1(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LearnApi.learnControllerRemoveV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a lesson (admin or instructor)
         * @param {string} id 
         * @param {UpdateLessonDto} updateLessonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async learnControllerUpdateV1(id: string, updateLessonDto: UpdateLessonDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.learnControllerUpdateV1(id, updateLessonDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LearnApi.learnControllerUpdateV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LearnApi - factory interface
 * @export
 */
export const LearnApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LearnApiFp(configuration)
    return {
        /**
         * 
         * @summary Mark a lesson as completed and award XP
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        learnControllerCompleteV1(slug: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.learnControllerCompleteV1(slug, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a lesson (admin or instructor)
         * @param {CreateLessonDto} createLessonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        learnControllerCreateV1(createLessonDto: CreateLessonDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.learnControllerCreateV1(createLessonDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get published lessons
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        learnControllerFindAllV1(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.learnControllerFindAllV1(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a lesson by slug with its content blocks
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        learnControllerFindBySlugV1(slug: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.learnControllerFindBySlugV1(slug, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a lesson (admin or instructor)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        learnControllerRemoveV1(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.learnControllerRemoveV1(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a lesson (admin or instructor)
         * @param {string} id 
         * @param {UpdateLessonDto} updateLessonDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        learnControllerUpdateV1(id: string, updateLessonDto: UpdateLessonDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.learnControllerUpdateV1(id, updateLessonDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LearnApi - object-oriented interface
 * @export
 * @class LearnApi
 * @extends {BaseAPI}
 */
export class LearnApi extends BaseAPI {
    /**
     * 
     * @summary Mark a lesson as completed and award XP
     * @param {string} slug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LearnApi
     */
    public learnControllerCompleteV1(slug: string, options?: RawAxiosRequestConfig) {
        return LearnApiFp(this.configuration).learnControllerCompleteV1(slug, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a lesson (admin or instructor)
     * @param {CreateLessonDto} createLessonDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LearnApi
     */
    public learnControllerCreateV1(createLessonDto: CreateLessonDto, options?: RawAxiosRequestConfig) {
        return LearnApiFp(this.configuration).learnControllerCreateV1(createLessonDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get published lessons
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LearnApi
     */
    public learnControllerFindAllV1(options?: RawAxiosRequestConfig) {
        return LearnApiFp(this.configuration).learnControllerFindAllV1(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a lesson by slug with its content blocks
     * @param {string} slug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LearnApi
     */
    public learnControllerFindBySlugV1(slug: string, options?: RawAxiosRequestConfig) {
        return LearnApiFp(this.configuration).learnControllerFindBySlugV1(slug, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a lesson (admin or instructor)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LearnApi
     */
    public learnControllerRemoveV1(id: string, options?: RawAxiosRequestConfig) {
        return LearnApiFp(this.configuration).learnControllerRemoveV1(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a lesson (admin or instructor)
     * @param {string} id 
     * @param {UpdateLessonDto} updateLessonDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LearnApi
     */
    public learnControllerUpdateV1(id: string, updateLessonDto: UpdateLessonDto, options?: RawAxiosRequestConfig) {
        return LearnApiFp(this.configuration).learnControllerUpdateV1(id, updateLessonDto, options).then((request) => request(this.axios, this.basePath));
    }
}



