/* tslint:disable */
/* eslint-disable */
/**
 * Courses API
 * Technicks Learn API with authentication, courses, and gamification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ChangePasswordDto
 */
export interface ChangePasswordDto {
    /**
     * Current password
     * @type {string}
     * @memberof ChangePasswordDto
     */
    'currentPassword': string;
    /**
     * New password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof ChangePasswordDto
     */
    'newPassword': string;
}
/**
 * 
 * @export
 * @interface CourseCheckInDto
 */
export interface CourseCheckInDto {
    /**
     * Local calendar date as YYYY-MM-DD. Defaults to server date.
     * @type {string}
     * @memberof CourseCheckInDto
     */
    'date'?: string;
}
/**
 * 
 * @export
 * @interface CreateCategoryDto
 */
export interface CreateCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'name': string;
    /**
     * Optional. Auto-generated from name if omitted.
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface CreateCommentDto
 */
export interface CreateCommentDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCommentDto
     */
    'body': string;
    /**
     * Parent comment ID for nested replies
     * @type {string}
     * @memberof CreateCommentDto
     */
    'parentId'?: string;
}
/**
 * 
 * @export
 * @interface CreateCourseCategoryDto
 */
export interface CreateCourseCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCourseCategoryDto
     */
    'name': string;
    /**
     * Optional. Auto-generated from name if omitted.
     * @type {string}
     * @memberof CreateCourseCategoryDto
     */
    'slug'?: string;
}
/**
 * 
 * @export
 * @interface CreateCourseDto
 */
export interface CreateCourseDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCourseDto
     */
    'title': string;
    /**
     * URL slug; defaults to a slugified title
     * @type {string}
     * @memberof CreateCourseDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseDto
     */
    'status'?: CreateCourseDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateCourseDto
     */
    'sortOrder'?: number;
    /**
     * CourseCategory id to assign; null clears it
     * @type {string}
     * @memberof CreateCourseDto
     */
    'categoryId'?: string;
}

export const CreateCourseDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED'
} as const;

export type CreateCourseDtoStatusEnum = typeof CreateCourseDtoStatusEnum[keyof typeof CreateCourseDtoStatusEnum];

/**
 * 
 * @export
 * @interface CreateLessonBlockDto
 */
export interface CreateLessonBlockDto {
    /**
     * Order of the block inside the lesson
     * @type {number}
     * @memberof CreateLessonBlockDto
     */
    'blockIndex'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonBlockDto
     */
    'kind': CreateLessonBlockDtoKindEnum;
    /**
     * Markdown/plain content for HEADING and TEXT blocks
     * @type {string}
     * @memberof CreateLessonBlockDto
     */
    'text'?: string;
    /**
     * Remote URL for IMAGE and VIDEO blocks
     * @type {string}
     * @memberof CreateLessonBlockDto
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonBlockDto
     */
    'caption'?: string;
}

export const CreateLessonBlockDtoKindEnum = {
    Heading: 'HEADING',
    Text: 'TEXT',
    Image: 'IMAGE',
    Video: 'VIDEO'
} as const;

export type CreateLessonBlockDtoKindEnum = typeof CreateLessonBlockDtoKindEnum[keyof typeof CreateLessonBlockDtoKindEnum];

/**
 * 
 * @export
 * @interface CreateLessonDto
 */
export interface CreateLessonDto {
    /**
     * 
     * @type {string}
     * @memberof CreateLessonDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonDto
     */
    'courseId': string;
    /**
     * URL slug; defaults to a slugified title
     * @type {string}
     * @memberof CreateLessonDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonDto
     */
    'status'?: CreateLessonDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateLessonDto
     */
    'sortOrder'?: number;
    /**
     * 
     * @type {Array<CreateLessonBlockDto>}
     * @memberof CreateLessonDto
     */
    'blocks'?: Array<CreateLessonBlockDto>;
}

export const CreateLessonDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED'
} as const;

export type CreateLessonDtoStatusEnum = typeof CreateLessonDtoStatusEnum[keyof typeof CreateLessonDtoStatusEnum];

/**
 * 
 * @export
 * @interface CreatePostDto
 */
export interface CreatePostDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'excerpt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'status'?: CreatePostDtoStatusEnum;
    /**
     * Array of category IDs
     * @type {Array<string>}
     * @memberof CreatePostDto
     */
    'categoryIds'?: Array<string>;
}

export const CreatePostDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;

export type CreatePostDtoStatusEnum = typeof CreatePostDtoStatusEnum[keyof typeof CreatePostDtoStatusEnum];

/**
 * 
 * @export
 * @interface ForgotPasswordDto
 */
export interface ForgotPasswordDto {
    /**
     * Email to send OTP to
     * @type {string}
     * @memberof ForgotPasswordDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface LoginDto
 */
export interface LoginDto {
    /**
     * User email address
     * @type {string}
     * @memberof LoginDto
     */
    'email': string;
    /**
     * User password
     * @type {string}
     * @memberof LoginDto
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
    /**
     * User email address
     * @type {string}
     * @memberof RegisterDto
     */
    'email': string;
    /**
     * Password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof RegisterDto
     */
    'password': string;
    /**
     * Full legal name
     * @type {string}
     * @memberof RegisterDto
     */
    'fullName'?: string;
}
/**
 * 
 * @export
 * @interface ResendOtpDto
 */
export interface ResendOtpDto {
    /**
     * Email pending verification to resend the OTP to
     * @type {string}
     * @memberof ResendOtpDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface ResetPasswordDto
 */
export interface ResetPasswordDto {
    /**
     * 6-digit OTP from email
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'token': string;
    /**
     * New password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'newPassword': string;
}
/**
 * 
 * @export
 * @interface SetUsernameDto
 */
export interface SetUsernameDto {
    /**
     * Desired username (3-30 chars, letters/numbers/underscores)
     * @type {string}
     * @memberof SetUsernameDto
     */
    'username': string;
}
/**
 * 
 * @export
 * @interface UpdateCategoryDto
 */
export interface UpdateCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'name'?: string;
    /**
     * Optional. Auto-generated from name if omitted.
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface UpdateCourseDto
 */
export interface UpdateCourseDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'status'?: UpdateCourseDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof UpdateCourseDto
     */
    'sortOrder'?: number;
    /**
     * CourseCategory id to assign; null clears it
     * @type {object}
     * @memberof UpdateCourseDto
     */
    'categoryId'?: object;
}

export const UpdateCourseDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED'
} as const;

export type UpdateCourseDtoStatusEnum = typeof UpdateCourseDtoStatusEnum[keyof typeof UpdateCourseDtoStatusEnum];

/**
 * 
 * @export
 * @interface UpdateLessonDto
 */
export interface UpdateLessonDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'courseId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'status'?: UpdateLessonDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof UpdateLessonDto
     */
    'sortOrder'?: number;
    /**
     * Replaces all blocks when provided
     * @type {Array<CreateLessonBlockDto>}
     * @memberof UpdateLessonDto
     */
    'blocks'?: Array<CreateLessonBlockDto>;
}

export const UpdateLessonDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED'
} as const;

export type UpdateLessonDtoStatusEnum = typeof UpdateLessonDtoStatusEnum[keyof typeof UpdateLessonDtoStatusEnum];

/**
 * 
 * @export
 * @interface UpdatePostDto
 */
export interface UpdatePostDto {
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'excerpt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'status'?: UpdatePostDtoStatusEnum;
    /**
     * Array of category IDs
     * @type {Array<string>}
     * @memberof UpdatePostDto
     */
    'categoryIds'?: Array<string>;
}

export const UpdatePostDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;

export type UpdatePostDtoStatusEnum = typeof UpdatePostDtoStatusEnum[keyof typeof UpdatePostDtoStatusEnum];

/**
 * 
 * @export
 * @interface VerifyEmailDto
 */
export interface VerifyEmailDto {
    /**
     * Email that received the verification OTP
     * @type {string}
     * @memberof VerifyEmailDto
     */
    'email': string;
    /**
     * 6-digit OTP sent to the email
     * @type {string}
     * @memberof VerifyEmailDto
     */
    'token': string;
}

/**
 * CoursesApi - axios parameter creator
 * @export
 */
export const CoursesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Daily course check-in — starts streak, awards XP
         * @param {string} slug 
         * @param {CourseCheckInDto} courseCheckInDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerCheckInV1: async (slug: string, courseCheckInDto: CourseCheckInDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('coursesControllerCheckInV1', 'slug', slug)
            // verify required parameter 'courseCheckInDto' is not null or undefined
            assertParamExists('coursesControllerCheckInV1', 'courseCheckInDto', courseCheckInDto)
            const localVarPath = `/api/v1/courses/{slug}/check-in`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(courseCheckInDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a course category (admin or instructor)
         * @param {CreateCourseCategoryDto} createCourseCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerCreateCategoryV1: async (createCourseCategoryDto: CreateCourseCategoryDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createCourseCategoryDto' is not null or undefined
            assertParamExists('coursesControllerCreateCategoryV1', 'createCourseCategoryDto', createCourseCategoryDto)
            const localVarPath = `/api/v1/courses/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCourseCategoryDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a course (admin or instructor)
         * @param {CreateCourseDto} createCourseDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerCreateV1: async (createCourseDto: CreateCourseDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createCourseDto' is not null or undefined
            assertParamExists('coursesControllerCreateV1', 'createCourseDto', createCourseDto)
            const localVarPath = `/api/v1/courses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCourseDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a course category (admin or instructor)
         * @param {string} id 
         * @param {boolean} [force] Detach from all courses before deleting
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerDeleteCategoryV1: async (id: string, force?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('coursesControllerDeleteCategoryV1', 'id', id)
            const localVarPath = `/api/v1/courses/categories/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (force !== undefined) {
                localVarQueryParameter['force'] = force;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Enroll in a course (idempotent)
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerEnrollV1: async (slug: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('coursesControllerEnrollV1', 'slug', slug)
            const localVarPath = `/api/v1/courses/{slug}/enroll`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Browse published courses with enrollment state
         * @param {string} [search] 
         * @param {string} [category] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerFindAllV1: async (search?: string, category?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/courses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Course detail with published lessons
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerFindBySlugV1: async (slug: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('coursesControllerFindBySlugV1', 'slug', slug)
            const localVarPath = `/api/v1/courses/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Courses you are enrolled in with streaks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerFindMineV1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/courses/mine`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all course categories (public)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerListCategoriesV1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/courses/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a course (admin or instructor)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerRemoveV1: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('coursesControllerRemoveV1', 'id', id)
            const localVarPath = `/api/v1/courses/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Unenroll from a course (deletes enrollment + check-ins)
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerUnenrollV1: async (slug: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('coursesControllerUnenrollV1', 'slug', slug)
            const localVarPath = `/api/v1/courses/{slug}/unenroll`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a course (admin or instructor)
         * @param {string} id 
         * @param {UpdateCourseDto} updateCourseDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerUpdateV1: async (id: string, updateCourseDto: UpdateCourseDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('coursesControllerUpdateV1', 'id', id)
            // verify required parameter 'updateCourseDto' is not null or undefined
            assertParamExists('coursesControllerUpdateV1', 'updateCourseDto', updateCourseDto)
            const localVarPath = `/api/v1/courses/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCourseDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CoursesApi - functional programming interface
 * @export
 */
export const CoursesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CoursesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Daily course check-in — starts streak, awards XP
         * @param {string} slug 
         * @param {CourseCheckInDto} courseCheckInDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coursesControllerCheckInV1(slug: string, courseCheckInDto: CourseCheckInDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coursesControllerCheckInV1(slug, courseCheckInDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.coursesControllerCheckInV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a course category (admin or instructor)
         * @param {CreateCourseCategoryDto} createCourseCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coursesControllerCreateCategoryV1(createCourseCategoryDto: CreateCourseCategoryDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coursesControllerCreateCategoryV1(createCourseCategoryDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.coursesControllerCreateCategoryV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a course (admin or instructor)
         * @param {CreateCourseDto} createCourseDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coursesControllerCreateV1(createCourseDto: CreateCourseDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coursesControllerCreateV1(createCourseDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.coursesControllerCreateV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a course category (admin or instructor)
         * @param {string} id 
         * @param {boolean} [force] Detach from all courses before deleting
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coursesControllerDeleteCategoryV1(id: string, force?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coursesControllerDeleteCategoryV1(id, force, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.coursesControllerDeleteCategoryV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Enroll in a course (idempotent)
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coursesControllerEnrollV1(slug: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coursesControllerEnrollV1(slug, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.coursesControllerEnrollV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Browse published courses with enrollment state
         * @param {string} [search] 
         * @param {string} [category] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coursesControllerFindAllV1(search?: string, category?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coursesControllerFindAllV1(search, category, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.coursesControllerFindAllV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Course detail with published lessons
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coursesControllerFindBySlugV1(slug: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coursesControllerFindBySlugV1(slug, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.coursesControllerFindBySlugV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Courses you are enrolled in with streaks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coursesControllerFindMineV1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coursesControllerFindMineV1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.coursesControllerFindMineV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all course categories (public)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coursesControllerListCategoriesV1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coursesControllerListCategoriesV1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.coursesControllerListCategoriesV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a course (admin or instructor)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coursesControllerRemoveV1(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coursesControllerRemoveV1(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.coursesControllerRemoveV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Unenroll from a course (deletes enrollment + check-ins)
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coursesControllerUnenrollV1(slug: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coursesControllerUnenrollV1(slug, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.coursesControllerUnenrollV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a course (admin or instructor)
         * @param {string} id 
         * @param {UpdateCourseDto} updateCourseDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coursesControllerUpdateV1(id: string, updateCourseDto: UpdateCourseDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coursesControllerUpdateV1(id, updateCourseDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.coursesControllerUpdateV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CoursesApi - factory interface
 * @export
 */
export const CoursesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CoursesApiFp(configuration)
    return {
        /**
         * 
         * @summary Daily course check-in — starts streak, awards XP
         * @param {string} slug 
         * @param {CourseCheckInDto} courseCheckInDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerCheckInV1(slug: string, courseCheckInDto: CourseCheckInDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.coursesControllerCheckInV1(slug, courseCheckInDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a course category (admin or instructor)
         * @param {CreateCourseCategoryDto} createCourseCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerCreateCategoryV1(createCourseCategoryDto: CreateCourseCategoryDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.coursesControllerCreateCategoryV1(createCourseCategoryDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a course (admin or instructor)
         * @param {CreateCourseDto} createCourseDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerCreateV1(createCourseDto: CreateCourseDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.coursesControllerCreateV1(createCourseDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a course category (admin or instructor)
         * @param {string} id 
         * @param {boolean} [force] Detach from all courses before deleting
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerDeleteCategoryV1(id: string, force?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.coursesControllerDeleteCategoryV1(id, force, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Enroll in a course (idempotent)
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerEnrollV1(slug: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.coursesControllerEnrollV1(slug, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Browse published courses with enrollment state
         * @param {string} [search] 
         * @param {string} [category] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerFindAllV1(search?: string, category?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.coursesControllerFindAllV1(search, category, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Course detail with published lessons
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerFindBySlugV1(slug: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.coursesControllerFindBySlugV1(slug, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Courses you are enrolled in with streaks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerFindMineV1(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.coursesControllerFindMineV1(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all course categories (public)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerListCategoriesV1(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.coursesControllerListCategoriesV1(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a course (admin or instructor)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerRemoveV1(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.coursesControllerRemoveV1(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Unenroll from a course (deletes enrollment + check-ins)
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerUnenrollV1(slug: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.coursesControllerUnenrollV1(slug, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a course (admin or instructor)
         * @param {string} id 
         * @param {UpdateCourseDto} updateCourseDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursesControllerUpdateV1(id: string, updateCourseDto: UpdateCourseDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.coursesControllerUpdateV1(id, updateCourseDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CoursesApi - object-oriented interface
 * @export
 * @class CoursesApi
 * @extends {BaseAPI}
 */
export class CoursesApi extends BaseAPI {
    /**
     * 
     * @summary Daily course check-in — starts streak, awards XP
     * @param {string} slug 
     * @param {CourseCheckInDto} courseCheckInDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public coursesControllerCheckInV1(slug: string, courseCheckInDto: CourseCheckInDto, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).coursesControllerCheckInV1(slug, courseCheckInDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a course category (admin or instructor)
     * @param {CreateCourseCategoryDto} createCourseCategoryDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public coursesControllerCreateCategoryV1(createCourseCategoryDto: CreateCourseCategoryDto, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).coursesControllerCreateCategoryV1(createCourseCategoryDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a course (admin or instructor)
     * @param {CreateCourseDto} createCourseDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public coursesControllerCreateV1(createCourseDto: CreateCourseDto, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).coursesControllerCreateV1(createCourseDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a course category (admin or instructor)
     * @param {string} id 
     * @param {boolean} [force] Detach from all courses before deleting
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public coursesControllerDeleteCategoryV1(id: string, force?: boolean, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).coursesControllerDeleteCategoryV1(id, force, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Enroll in a course (idempotent)
     * @param {string} slug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public coursesControllerEnrollV1(slug: string, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).coursesControllerEnrollV1(slug, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Browse published courses with enrollment state
     * @param {string} [search] 
     * @param {string} [category] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public coursesControllerFindAllV1(search?: string, category?: string, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).coursesControllerFindAllV1(search, category, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Course detail with published lessons
     * @param {string} slug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public coursesControllerFindBySlugV1(slug: string, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).coursesControllerFindBySlugV1(slug, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Courses you are enrolled in with streaks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public coursesControllerFindMineV1(options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).coursesControllerFindMineV1(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all course categories (public)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public coursesControllerListCategoriesV1(options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).coursesControllerListCategoriesV1(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a course (admin or instructor)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public coursesControllerRemoveV1(id: string, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).coursesControllerRemoveV1(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Unenroll from a course (deletes enrollment + check-ins)
     * @param {string} slug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public coursesControllerUnenrollV1(slug: string, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).coursesControllerUnenrollV1(slug, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a course (admin or instructor)
     * @param {string} id 
     * @param {UpdateCourseDto} updateCourseDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public coursesControllerUpdateV1(id: string, updateCourseDto: UpdateCourseDto, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).coursesControllerUpdateV1(id, updateCourseDto, options).then((request) => request(this.axios, this.basePath));
    }
}



