/* tslint:disable */
/* eslint-disable */
/**
 * Blog API
 * Technicks Learn API with authentication, courses, and gamification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ChangePasswordDto
 */
export interface ChangePasswordDto {
    /**
     * Current password
     * @type {string}
     * @memberof ChangePasswordDto
     */
    'currentPassword': string;
    /**
     * New password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof ChangePasswordDto
     */
    'newPassword': string;
}
/**
 * 
 * @export
 * @interface CreateCategoryDto
 */
export interface CreateCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'name': string;
    /**
     * Optional. Auto-generated from name if omitted.
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface CreateCommentDto
 */
export interface CreateCommentDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCommentDto
     */
    'body': string;
    /**
     * Parent comment ID for nested replies
     * @type {string}
     * @memberof CreateCommentDto
     */
    'parentId'?: string;
}
/**
 * 
 * @export
 * @interface CreatePostDto
 */
export interface CreatePostDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'excerpt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'status'?: CreatePostDtoStatusEnum;
    /**
     * Array of category IDs
     * @type {Array<string>}
     * @memberof CreatePostDto
     */
    'categoryIds'?: Array<string>;
}

export const CreatePostDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;

export type CreatePostDtoStatusEnum = typeof CreatePostDtoStatusEnum[keyof typeof CreatePostDtoStatusEnum];

/**
 * 
 * @export
 * @interface ForgotPasswordDto
 */
export interface ForgotPasswordDto {
    /**
     * Email to send OTP to
     * @type {string}
     * @memberof ForgotPasswordDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface LoginDto
 */
export interface LoginDto {
    /**
     * User email address
     * @type {string}
     * @memberof LoginDto
     */
    'email': string;
    /**
     * User password
     * @type {string}
     * @memberof LoginDto
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
    /**
     * User email address
     * @type {string}
     * @memberof RegisterDto
     */
    'email': string;
    /**
     * Password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof RegisterDto
     */
    'password': string;
    /**
     * Full legal name
     * @type {string}
     * @memberof RegisterDto
     */
    'fullName'?: string;
}
/**
 * 
 * @export
 * @interface ResendOtpDto
 */
export interface ResendOtpDto {
    /**
     * Email pending verification to resend the OTP to
     * @type {string}
     * @memberof ResendOtpDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface ResetPasswordDto
 */
export interface ResetPasswordDto {
    /**
     * 6-digit OTP from email
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'token': string;
    /**
     * New password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'newPassword': string;
}
/**
 * 
 * @export
 * @interface SetUsernameDto
 */
export interface SetUsernameDto {
    /**
     * Desired username (3-30 chars, letters/numbers/underscores)
     * @type {string}
     * @memberof SetUsernameDto
     */
    'username': string;
}
/**
 * 
 * @export
 * @interface UpdateCategoryDto
 */
export interface UpdateCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'name'?: string;
    /**
     * Optional. Auto-generated from name if omitted.
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface UpdatePostDto
 */
export interface UpdatePostDto {
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'excerpt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'status'?: UpdatePostDtoStatusEnum;
    /**
     * Array of category IDs
     * @type {Array<string>}
     * @memberof UpdatePostDto
     */
    'categoryIds'?: Array<string>;
}

export const UpdatePostDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;

export type UpdatePostDtoStatusEnum = typeof UpdatePostDtoStatusEnum[keyof typeof UpdatePostDtoStatusEnum];

/**
 * 
 * @export
 * @interface VerifyEmailDto
 */
export interface VerifyEmailDto {
    /**
     * Email that received the verification OTP
     * @type {string}
     * @memberof VerifyEmailDto
     */
    'email': string;
    /**
     * 6-digit OTP sent to the email
     * @type {string}
     * @memberof VerifyEmailDto
     */
    'token': string;
}

/**
 * BlogApi - axios parameter creator
 * @export
 */
export const BlogApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add a comment to a blog post
         * @param {string} id 
         * @param {CreateCommentDto} createCommentDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerCreateCommentV1: async (id: string, createCommentDto: CreateCommentDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('blogControllerCreateCommentV1', 'id', id)
            // verify required parameter 'createCommentDto' is not null or undefined
            assertParamExists('blogControllerCreateCommentV1', 'createCommentDto', createCommentDto)
            const localVarPath = `/api/v1/blogs/{id}/comments`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCommentDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a blog post
         * @param {CreatePostDto} createPostDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerCreateV1: async (createPostDto: CreatePostDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createPostDto' is not null or undefined
            assertParamExists('blogControllerCreateV1', 'createPostDto', createPostDto)
            const localVarPath = `/api/v1/blogs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createPostDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get published blog posts (public)
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {string} [category] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerFindAllV1: async (page?: number, limit?: number, category?: string, search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/blogs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a blog post by slug
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerFindBySlugV1: async (slug: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('blogControllerFindBySlugV1', 'slug', slug)
            const localVarPath = `/api/v1/blogs/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get the current user\'s blog posts (any status)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerFindMineV1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/blogs/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get comments for a blog post
         * @param {string} id 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerGetCommentsV1: async (id: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('blogControllerGetCommentsV1', 'id', id)
            const localVarPath = `/api/v1/blogs/{id}/comments`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a comment (author or admin)
         * @param {string} postId 
         * @param {string} commentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerRemoveCommentV1: async (postId: string, commentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postId' is not null or undefined
            assertParamExists('blogControllerRemoveCommentV1', 'postId', postId)
            // verify required parameter 'commentId' is not null or undefined
            assertParamExists('blogControllerRemoveCommentV1', 'commentId', commentId)
            const localVarPath = `/api/v1/blogs/{postId}/comments/{commentId}`
                .replace(`{${"postId"}}`, encodeURIComponent(String(postId)))
                .replace(`{${"commentId"}}`, encodeURIComponent(String(commentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a blog post (author or admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerRemoveV1: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('blogControllerRemoveV1', 'id', id)
            const localVarPath = `/api/v1/blogs/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Toggle like on a blog post
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerToggleLikeV1: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('blogControllerToggleLikeV1', 'id', id)
            const localVarPath = `/api/v1/blogs/{id}/like`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a blog post (author only)
         * @param {string} id 
         * @param {UpdatePostDto} updatePostDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerUpdateV1: async (id: string, updatePostDto: UpdatePostDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('blogControllerUpdateV1', 'id', id)
            // verify required parameter 'updatePostDto' is not null or undefined
            assertParamExists('blogControllerUpdateV1', 'updatePostDto', updatePostDto)
            const localVarPath = `/api/v1/blogs/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updatePostDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BlogApi - functional programming interface
 * @export
 */
export const BlogApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BlogApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add a comment to a blog post
         * @param {string} id 
         * @param {CreateCommentDto} createCommentDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async blogControllerCreateCommentV1(id: string, createCommentDto: CreateCommentDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.blogControllerCreateCommentV1(id, createCommentDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogApi.blogControllerCreateCommentV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a blog post
         * @param {CreatePostDto} createPostDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async blogControllerCreateV1(createPostDto: CreatePostDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.blogControllerCreateV1(createPostDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogApi.blogControllerCreateV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get published blog posts (public)
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {string} [category] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async blogControllerFindAllV1(page?: number, limit?: number, category?: string, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.blogControllerFindAllV1(page, limit, category, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogApi.blogControllerFindAllV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a blog post by slug
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async blogControllerFindBySlugV1(slug: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.blogControllerFindBySlugV1(slug, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogApi.blogControllerFindBySlugV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get the current user\'s blog posts (any status)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async blogControllerFindMineV1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.blogControllerFindMineV1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogApi.blogControllerFindMineV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get comments for a blog post
         * @param {string} id 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async blogControllerGetCommentsV1(id: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.blogControllerGetCommentsV1(id, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogApi.blogControllerGetCommentsV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a comment (author or admin)
         * @param {string} postId 
         * @param {string} commentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async blogControllerRemoveCommentV1(postId: string, commentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.blogControllerRemoveCommentV1(postId, commentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogApi.blogControllerRemoveCommentV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a blog post (author or admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async blogControllerRemoveV1(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.blogControllerRemoveV1(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogApi.blogControllerRemoveV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Toggle like on a blog post
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async blogControllerToggleLikeV1(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.blogControllerToggleLikeV1(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogApi.blogControllerToggleLikeV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a blog post (author only)
         * @param {string} id 
         * @param {UpdatePostDto} updatePostDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async blogControllerUpdateV1(id: string, updatePostDto: UpdatePostDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.blogControllerUpdateV1(id, updatePostDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogApi.blogControllerUpdateV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BlogApi - factory interface
 * @export
 */
export const BlogApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BlogApiFp(configuration)
    return {
        /**
         * 
         * @summary Add a comment to a blog post
         * @param {string} id 
         * @param {CreateCommentDto} createCommentDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerCreateCommentV1(id: string, createCommentDto: CreateCommentDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.blogControllerCreateCommentV1(id, createCommentDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a blog post
         * @param {CreatePostDto} createPostDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerCreateV1(createPostDto: CreatePostDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.blogControllerCreateV1(createPostDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get published blog posts (public)
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {string} [category] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerFindAllV1(page?: number, limit?: number, category?: string, search?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.blogControllerFindAllV1(page, limit, category, search, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a blog post by slug
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerFindBySlugV1(slug: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.blogControllerFindBySlugV1(slug, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get the current user\'s blog posts (any status)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerFindMineV1(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.blogControllerFindMineV1(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get comments for a blog post
         * @param {string} id 
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerGetCommentsV1(id: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.blogControllerGetCommentsV1(id, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a comment (author or admin)
         * @param {string} postId 
         * @param {string} commentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerRemoveCommentV1(postId: string, commentId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.blogControllerRemoveCommentV1(postId, commentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a blog post (author or admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerRemoveV1(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.blogControllerRemoveV1(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Toggle like on a blog post
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerToggleLikeV1(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.blogControllerToggleLikeV1(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a blog post (author only)
         * @param {string} id 
         * @param {UpdatePostDto} updatePostDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blogControllerUpdateV1(id: string, updatePostDto: UpdatePostDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.blogControllerUpdateV1(id, updatePostDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BlogApi - object-oriented interface
 * @export
 * @class BlogApi
 * @extends {BaseAPI}
 */
export class BlogApi extends BaseAPI {
    /**
     * 
     * @summary Add a comment to a blog post
     * @param {string} id 
     * @param {CreateCommentDto} createCommentDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogApi
     */
    public blogControllerCreateCommentV1(id: string, createCommentDto: CreateCommentDto, options?: RawAxiosRequestConfig) {
        return BlogApiFp(this.configuration).blogControllerCreateCommentV1(id, createCommentDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a blog post
     * @param {CreatePostDto} createPostDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogApi
     */
    public blogControllerCreateV1(createPostDto: CreatePostDto, options?: RawAxiosRequestConfig) {
        return BlogApiFp(this.configuration).blogControllerCreateV1(createPostDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get published blog posts (public)
     * @param {number} [page] 
     * @param {number} [limit] 
     * @param {string} [category] 
     * @param {string} [search] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogApi
     */
    public blogControllerFindAllV1(page?: number, limit?: number, category?: string, search?: string, options?: RawAxiosRequestConfig) {
        return BlogApiFp(this.configuration).blogControllerFindAllV1(page, limit, category, search, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a blog post by slug
     * @param {string} slug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogApi
     */
    public blogControllerFindBySlugV1(slug: string, options?: RawAxiosRequestConfig) {
        return BlogApiFp(this.configuration).blogControllerFindBySlugV1(slug, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get the current user\'s blog posts (any status)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogApi
     */
    public blogControllerFindMineV1(options?: RawAxiosRequestConfig) {
        return BlogApiFp(this.configuration).blogControllerFindMineV1(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get comments for a blog post
     * @param {string} id 
     * @param {number} [page] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogApi
     */
    public blogControllerGetCommentsV1(id: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return BlogApiFp(this.configuration).blogControllerGetCommentsV1(id, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a comment (author or admin)
     * @param {string} postId 
     * @param {string} commentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogApi
     */
    public blogControllerRemoveCommentV1(postId: string, commentId: string, options?: RawAxiosRequestConfig) {
        return BlogApiFp(this.configuration).blogControllerRemoveCommentV1(postId, commentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a blog post (author or admin)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogApi
     */
    public blogControllerRemoveV1(id: string, options?: RawAxiosRequestConfig) {
        return BlogApiFp(this.configuration).blogControllerRemoveV1(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Toggle like on a blog post
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogApi
     */
    public blogControllerToggleLikeV1(id: string, options?: RawAxiosRequestConfig) {
        return BlogApiFp(this.configuration).blogControllerToggleLikeV1(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a blog post (author only)
     * @param {string} id 
     * @param {UpdatePostDto} updatePostDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogApi
     */
    public blogControllerUpdateV1(id: string, updatePostDto: UpdatePostDto, options?: RawAxiosRequestConfig) {
        return BlogApiFp(this.configuration).blogControllerUpdateV1(id, updatePostDto, options).then((request) => request(this.axios, this.basePath));
    }
}



