/* tslint:disable */
/* eslint-disable */
/**
 * Gamification API
 * Technicks Learn API with authentication, courses, and gamification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ChangePasswordDto
 */
export interface ChangePasswordDto {
    /**
     * Current password
     * @type {string}
     * @memberof ChangePasswordDto
     */
    'currentPassword': string;
    /**
     * New password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof ChangePasswordDto
     */
    'newPassword': string;
}
/**
 * 
 * @export
 * @interface CourseCheckInDto
 */
export interface CourseCheckInDto {
    /**
     * Local calendar date as YYYY-MM-DD. Defaults to server date.
     * @type {string}
     * @memberof CourseCheckInDto
     */
    'date'?: string;
}
/**
 * 
 * @export
 * @interface CreateCategoryDto
 */
export interface CreateCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'name': string;
    /**
     * Optional. Auto-generated from name if omitted.
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface CreateCommentDto
 */
export interface CreateCommentDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCommentDto
     */
    'body': string;
    /**
     * Parent comment ID for nested replies
     * @type {string}
     * @memberof CreateCommentDto
     */
    'parentId'?: string;
}
/**
 * 
 * @export
 * @interface CreateCourseDto
 */
export interface CreateCourseDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCourseDto
     */
    'title': string;
    /**
     * URL slug; defaults to a slugified title
     * @type {string}
     * @memberof CreateCourseDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCourseDto
     */
    'status'?: CreateCourseDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateCourseDto
     */
    'sortOrder'?: number;
}

export const CreateCourseDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED'
} as const;

export type CreateCourseDtoStatusEnum = typeof CreateCourseDtoStatusEnum[keyof typeof CreateCourseDtoStatusEnum];

/**
 * 
 * @export
 * @interface CreateLessonBlockDto
 */
export interface CreateLessonBlockDto {
    /**
     * Order of the block inside the lesson
     * @type {number}
     * @memberof CreateLessonBlockDto
     */
    'blockIndex'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonBlockDto
     */
    'kind': CreateLessonBlockDtoKindEnum;
    /**
     * Markdown/plain content for HEADING and TEXT blocks
     * @type {string}
     * @memberof CreateLessonBlockDto
     */
    'text'?: string;
    /**
     * Remote URL for IMAGE and VIDEO blocks
     * @type {string}
     * @memberof CreateLessonBlockDto
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonBlockDto
     */
    'caption'?: string;
}

export const CreateLessonBlockDtoKindEnum = {
    Heading: 'HEADING',
    Text: 'TEXT',
    Image: 'IMAGE',
    Video: 'VIDEO'
} as const;

export type CreateLessonBlockDtoKindEnum = typeof CreateLessonBlockDtoKindEnum[keyof typeof CreateLessonBlockDtoKindEnum];

/**
 * 
 * @export
 * @interface CreateLessonDto
 */
export interface CreateLessonDto {
    /**
     * 
     * @type {string}
     * @memberof CreateLessonDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonDto
     */
    'courseId': string;
    /**
     * URL slug; defaults to a slugified title
     * @type {string}
     * @memberof CreateLessonDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLessonDto
     */
    'status'?: CreateLessonDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateLessonDto
     */
    'sortOrder'?: number;
    /**
     * 
     * @type {Array<CreateLessonBlockDto>}
     * @memberof CreateLessonDto
     */
    'blocks'?: Array<CreateLessonBlockDto>;
}

export const CreateLessonDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED'
} as const;

export type CreateLessonDtoStatusEnum = typeof CreateLessonDtoStatusEnum[keyof typeof CreateLessonDtoStatusEnum];

/**
 * 
 * @export
 * @interface CreatePostDto
 */
export interface CreatePostDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'excerpt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'status'?: CreatePostDtoStatusEnum;
    /**
     * Array of category IDs
     * @type {Array<string>}
     * @memberof CreatePostDto
     */
    'categoryIds'?: Array<string>;
}

export const CreatePostDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;

export type CreatePostDtoStatusEnum = typeof CreatePostDtoStatusEnum[keyof typeof CreatePostDtoStatusEnum];

/**
 * 
 * @export
 * @interface ForgotPasswordDto
 */
export interface ForgotPasswordDto {
    /**
     * Email to send OTP to
     * @type {string}
     * @memberof ForgotPasswordDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface LoginDto
 */
export interface LoginDto {
    /**
     * User email address
     * @type {string}
     * @memberof LoginDto
     */
    'email': string;
    /**
     * User password
     * @type {string}
     * @memberof LoginDto
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
    /**
     * User email address
     * @type {string}
     * @memberof RegisterDto
     */
    'email': string;
    /**
     * Password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof RegisterDto
     */
    'password': string;
    /**
     * Full legal name
     * @type {string}
     * @memberof RegisterDto
     */
    'fullName'?: string;
}
/**
 * 
 * @export
 * @interface ResendOtpDto
 */
export interface ResendOtpDto {
    /**
     * Email pending verification to resend the OTP to
     * @type {string}
     * @memberof ResendOtpDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface ResetPasswordDto
 */
export interface ResetPasswordDto {
    /**
     * 6-digit OTP from email
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'token': string;
    /**
     * New password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'newPassword': string;
}
/**
 * 
 * @export
 * @interface SetUsernameDto
 */
export interface SetUsernameDto {
    /**
     * Desired username (3-30 chars, letters/numbers/underscores)
     * @type {string}
     * @memberof SetUsernameDto
     */
    'username': string;
}
/**
 * 
 * @export
 * @interface UpdateCategoryDto
 */
export interface UpdateCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'name'?: string;
    /**
     * Optional. Auto-generated from name if omitted.
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface UpdateCourseDto
 */
export interface UpdateCourseDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCourseDto
     */
    'status'?: UpdateCourseDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof UpdateCourseDto
     */
    'sortOrder'?: number;
}

export const UpdateCourseDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED'
} as const;

export type UpdateCourseDtoStatusEnum = typeof UpdateCourseDtoStatusEnum[keyof typeof UpdateCourseDtoStatusEnum];

/**
 * 
 * @export
 * @interface UpdateLessonDto
 */
export interface UpdateLessonDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'courseId'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateLessonDto
     */
    'status'?: UpdateLessonDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof UpdateLessonDto
     */
    'sortOrder'?: number;
    /**
     * Replaces all blocks when provided
     * @type {Array<CreateLessonBlockDto>}
     * @memberof UpdateLessonDto
     */
    'blocks'?: Array<CreateLessonBlockDto>;
}

export const UpdateLessonDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED'
} as const;

export type UpdateLessonDtoStatusEnum = typeof UpdateLessonDtoStatusEnum[keyof typeof UpdateLessonDtoStatusEnum];

/**
 * 
 * @export
 * @interface UpdatePostDto
 */
export interface UpdatePostDto {
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'excerpt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'status'?: UpdatePostDtoStatusEnum;
    /**
     * Array of category IDs
     * @type {Array<string>}
     * @memberof UpdatePostDto
     */
    'categoryIds'?: Array<string>;
}

export const UpdatePostDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;

export type UpdatePostDtoStatusEnum = typeof UpdatePostDtoStatusEnum[keyof typeof UpdatePostDtoStatusEnum];

/**
 * 
 * @export
 * @interface VerifyEmailDto
 */
export interface VerifyEmailDto {
    /**
     * Email that received the verification OTP
     * @type {string}
     * @memberof VerifyEmailDto
     */
    'email': string;
    /**
     * 6-digit OTP sent to the email
     * @type {string}
     * @memberof VerifyEmailDto
     */
    'token': string;
}

/**
 * GamificationApi - axios parameter creator
 * @export
 */
export const GamificationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get your total XP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gamificationControllerGetMeV1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/gamification/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get the current week\'s leaderboard with tiers
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gamificationControllerLeaderboardV1: async (limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/gamification/leaderboard`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GamificationApi - functional programming interface
 * @export
 */
export const GamificationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GamificationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get your total XP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gamificationControllerGetMeV1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gamificationControllerGetMeV1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GamificationApi.gamificationControllerGetMeV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get the current week\'s leaderboard with tiers
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gamificationControllerLeaderboardV1(limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gamificationControllerLeaderboardV1(limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GamificationApi.gamificationControllerLeaderboardV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GamificationApi - factory interface
 * @export
 */
export const GamificationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GamificationApiFp(configuration)
    return {
        /**
         * 
         * @summary Get your total XP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gamificationControllerGetMeV1(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.gamificationControllerGetMeV1(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get the current week\'s leaderboard with tiers
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gamificationControllerLeaderboardV1(limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.gamificationControllerLeaderboardV1(limit, offset, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GamificationApi - object-oriented interface
 * @export
 * @class GamificationApi
 * @extends {BaseAPI}
 */
export class GamificationApi extends BaseAPI {
    /**
     * 
     * @summary Get your total XP
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamificationApi
     */
    public gamificationControllerGetMeV1(options?: RawAxiosRequestConfig) {
        return GamificationApiFp(this.configuration).gamificationControllerGetMeV1(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get the current week\'s leaderboard with tiers
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamificationApi
     */
    public gamificationControllerLeaderboardV1(limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return GamificationApiFp(this.configuration).gamificationControllerLeaderboardV1(limit, offset, options).then((request) => request(this.axios, this.basePath));
    }
}



