/* tslint:disable */
/* eslint-disable */
/**
 * Blog Categories API
 * Technicks Learn API with authentication, courses, and gamification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ChangePasswordDto
 */
export interface ChangePasswordDto {
    /**
     * Current password
     * @type {string}
     * @memberof ChangePasswordDto
     */
    'currentPassword': string;
    /**
     * New password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof ChangePasswordDto
     */
    'newPassword': string;
}
/**
 * 
 * @export
 * @interface CreateCategoryDto
 */
export interface CreateCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'name': string;
    /**
     * Optional. Auto-generated from name if omitted.
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface CreateCommentDto
 */
export interface CreateCommentDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCommentDto
     */
    'body': string;
    /**
     * Parent comment ID for nested replies
     * @type {string}
     * @memberof CreateCommentDto
     */
    'parentId'?: string;
}
/**
 * 
 * @export
 * @interface CreatePostDto
 */
export interface CreatePostDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'excerpt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostDto
     */
    'status'?: CreatePostDtoStatusEnum;
    /**
     * Array of category IDs
     * @type {Array<string>}
     * @memberof CreatePostDto
     */
    'categoryIds'?: Array<string>;
}

export const CreatePostDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;

export type CreatePostDtoStatusEnum = typeof CreatePostDtoStatusEnum[keyof typeof CreatePostDtoStatusEnum];

/**
 * 
 * @export
 * @interface ForgotPasswordDto
 */
export interface ForgotPasswordDto {
    /**
     * Email to send OTP to
     * @type {string}
     * @memberof ForgotPasswordDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface LoginDto
 */
export interface LoginDto {
    /**
     * User email address
     * @type {string}
     * @memberof LoginDto
     */
    'email': string;
    /**
     * User password
     * @type {string}
     * @memberof LoginDto
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
    /**
     * User email address
     * @type {string}
     * @memberof RegisterDto
     */
    'email': string;
    /**
     * Password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof RegisterDto
     */
    'password': string;
    /**
     * Full legal name
     * @type {string}
     * @memberof RegisterDto
     */
    'fullName'?: string;
}
/**
 * 
 * @export
 * @interface ResendOtpDto
 */
export interface ResendOtpDto {
    /**
     * Email pending verification to resend the OTP to
     * @type {string}
     * @memberof ResendOtpDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface ResetPasswordDto
 */
export interface ResetPasswordDto {
    /**
     * 6-digit OTP from email
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'token': string;
    /**
     * New password (min 8 chars, must include uppercase, lowercase, number)
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'newPassword': string;
}
/**
 * 
 * @export
 * @interface SetUsernameDto
 */
export interface SetUsernameDto {
    /**
     * Desired username (3-30 chars, letters/numbers/underscores)
     * @type {string}
     * @memberof SetUsernameDto
     */
    'username': string;
}
/**
 * 
 * @export
 * @interface UpdateCategoryDto
 */
export interface UpdateCategoryDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'name'?: string;
    /**
     * Optional. Auto-generated from name if omitted.
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCategoryDto
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface UpdatePostDto
 */
export interface UpdatePostDto {
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'excerpt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'coverImage'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostDto
     */
    'status'?: UpdatePostDtoStatusEnum;
    /**
     * Array of category IDs
     * @type {Array<string>}
     * @memberof UpdatePostDto
     */
    'categoryIds'?: Array<string>;
}

export const UpdatePostDtoStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;

export type UpdatePostDtoStatusEnum = typeof UpdatePostDtoStatusEnum[keyof typeof UpdatePostDtoStatusEnum];

/**
 * 
 * @export
 * @interface VerifyEmailDto
 */
export interface VerifyEmailDto {
    /**
     * Email that received the verification OTP
     * @type {string}
     * @memberof VerifyEmailDto
     */
    'email': string;
    /**
     * 6-digit OTP sent to the email
     * @type {string}
     * @memberof VerifyEmailDto
     */
    'token': string;
}

/**
 * BlogCategoriesApi - axios parameter creator
 * @export
 */
export const BlogCategoriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a category (admin only)
         * @param {CreateCategoryDto} createCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoryControllerCreateV1: async (createCategoryDto: CreateCategoryDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createCategoryDto' is not null or undefined
            assertParamExists('categoryControllerCreateV1', 'createCategoryDto', createCategoryDto)
            const localVarPath = `/api/v1/blogs/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCategoryDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all blog categories (public)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoryControllerFindAllV1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/blogs/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a category by id or slug (public)
         * @param {string} identifier 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoryControllerFindOneV1: async (identifier: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'identifier' is not null or undefined
            assertParamExists('categoryControllerFindOneV1', 'identifier', identifier)
            const localVarPath = `/api/v1/blogs/categories/{identifier}`
                .replace(`{${"identifier"}}`, encodeURIComponent(String(identifier)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a category (admin only)
         * @param {string} id 
         * @param {boolean} [force] Detach from all posts before deleting
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoryControllerRemoveV1: async (id: string, force?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('categoryControllerRemoveV1', 'id', id)
            const localVarPath = `/api/v1/blogs/categories/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (force !== undefined) {
                localVarQueryParameter['force'] = force;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a category (admin only)
         * @param {string} id 
         * @param {UpdateCategoryDto} updateCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoryControllerUpdateV1: async (id: string, updateCategoryDto: UpdateCategoryDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('categoryControllerUpdateV1', 'id', id)
            // verify required parameter 'updateCategoryDto' is not null or undefined
            assertParamExists('categoryControllerUpdateV1', 'updateCategoryDto', updateCategoryDto)
            const localVarPath = `/api/v1/blogs/categories/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication access-token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCategoryDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BlogCategoriesApi - functional programming interface
 * @export
 */
export const BlogCategoriesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BlogCategoriesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a category (admin only)
         * @param {CreateCategoryDto} createCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoryControllerCreateV1(createCategoryDto: CreateCategoryDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoryControllerCreateV1(createCategoryDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogCategoriesApi.categoryControllerCreateV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all blog categories (public)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoryControllerFindAllV1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoryControllerFindAllV1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogCategoriesApi.categoryControllerFindAllV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a category by id or slug (public)
         * @param {string} identifier 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoryControllerFindOneV1(identifier: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoryControllerFindOneV1(identifier, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogCategoriesApi.categoryControllerFindOneV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a category (admin only)
         * @param {string} id 
         * @param {boolean} [force] Detach from all posts before deleting
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoryControllerRemoveV1(id: string, force?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoryControllerRemoveV1(id, force, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogCategoriesApi.categoryControllerRemoveV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a category (admin only)
         * @param {string} id 
         * @param {UpdateCategoryDto} updateCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoryControllerUpdateV1(id: string, updateCategoryDto: UpdateCategoryDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoryControllerUpdateV1(id, updateCategoryDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlogCategoriesApi.categoryControllerUpdateV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BlogCategoriesApi - factory interface
 * @export
 */
export const BlogCategoriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BlogCategoriesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a category (admin only)
         * @param {CreateCategoryDto} createCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoryControllerCreateV1(createCategoryDto: CreateCategoryDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.categoryControllerCreateV1(createCategoryDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all blog categories (public)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoryControllerFindAllV1(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.categoryControllerFindAllV1(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a category by id or slug (public)
         * @param {string} identifier 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoryControllerFindOneV1(identifier: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.categoryControllerFindOneV1(identifier, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a category (admin only)
         * @param {string} id 
         * @param {boolean} [force] Detach from all posts before deleting
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoryControllerRemoveV1(id: string, force?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.categoryControllerRemoveV1(id, force, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a category (admin only)
         * @param {string} id 
         * @param {UpdateCategoryDto} updateCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoryControllerUpdateV1(id: string, updateCategoryDto: UpdateCategoryDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.categoryControllerUpdateV1(id, updateCategoryDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BlogCategoriesApi - object-oriented interface
 * @export
 * @class BlogCategoriesApi
 * @extends {BaseAPI}
 */
export class BlogCategoriesApi extends BaseAPI {
    /**
     * 
     * @summary Create a category (admin only)
     * @param {CreateCategoryDto} createCategoryDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogCategoriesApi
     */
    public categoryControllerCreateV1(createCategoryDto: CreateCategoryDto, options?: RawAxiosRequestConfig) {
        return BlogCategoriesApiFp(this.configuration).categoryControllerCreateV1(createCategoryDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all blog categories (public)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogCategoriesApi
     */
    public categoryControllerFindAllV1(options?: RawAxiosRequestConfig) {
        return BlogCategoriesApiFp(this.configuration).categoryControllerFindAllV1(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a category by id or slug (public)
     * @param {string} identifier 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogCategoriesApi
     */
    public categoryControllerFindOneV1(identifier: string, options?: RawAxiosRequestConfig) {
        return BlogCategoriesApiFp(this.configuration).categoryControllerFindOneV1(identifier, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a category (admin only)
     * @param {string} id 
     * @param {boolean} [force] Detach from all posts before deleting
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogCategoriesApi
     */
    public categoryControllerRemoveV1(id: string, force?: boolean, options?: RawAxiosRequestConfig) {
        return BlogCategoriesApiFp(this.configuration).categoryControllerRemoveV1(id, force, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a category (admin only)
     * @param {string} id 
     * @param {UpdateCategoryDto} updateCategoryDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlogCategoriesApi
     */
    public categoryControllerUpdateV1(id: string, updateCategoryDto: UpdateCategoryDto, options?: RawAxiosRequestConfig) {
        return BlogCategoriesApiFp(this.configuration).categoryControllerUpdateV1(id, updateCategoryDto, options).then((request) => request(this.axios, this.basePath));
    }
}



